# Generated by Django 5.2.5 on 2025-08-19 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='meesage',
            new_name='message',
        ),
    ]
