# Generated by Django 5.2.5 on 2025-08-19 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_counted_views_post_created_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-created_date',)},
        ),
        migrations.AlterModelTable(
            name='post',
            table='blog_post',
        ),
    ]
